spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.10.151/datum_admin_lsy?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: metis_admin
      password: admin_123456
  # =============================== consul ===============================
  cloud:
    consul:
      host: 39.101.171.59
      port: 8500
      discovery:  # 服务发现配置
        instance-id: adminService_39.101.171.59_90901

# ==================================== server conf  ==========================================
server:
  port: 9090

# =============================== conf for logger ===================================
# 日志配置
logging:
  file:
    # 日志文件名格式
    name: ./logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
      file-name-pattern: ./logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz

#调用pinata接口的jwt
pinata-token: xxx
#pinata的网关地址
pinata-gateway: https://datumdev.mypinata.cloud/
#pinata的上传文件域名
pinata-url: https://api.pinata.cloud/

#无属性数据凭证消耗量更新间隔，单位分钟
dataToken-updateFee-interval: 5

# ==================================== conf for grpc =====================================
grpc:
  server:
    port: 9091
    in-process-name: datum-admin-server
    max-inbound-message-size: 1073741824
  client:
    #允许客户端在同一应用程序内使用以下配置连接到服务器
    inProcess:
      address: in-process:datum-admin-server