spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.9.192:3306/dev_metis_admin_3.0?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: platon
      password: platon
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 60000
      connection-init-sqls: set names utf8mb4
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # =============================== consul ===============================
  cloud:
    consul:
      host: 10.1.1.10
      port: 8500
      discovery:  # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # 应用名称+服务器IP+端口
        tags: ${spring.application.name}
        health-check-interval: 10s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/${server.servlet.context-path}/health
        # health-check-path: ${management.endpoints.web.base-path}/health
      carrierServiceName: carrierService
# ==================================== server conf  ==========================================
server:
  tomcat:
    uri-encoding: UTF-8
    threads.max: 1000
    threads.min-spare: 30
  port: 8080
  servlet:
    context-path: /metis-admin


# =============================== conf for logger ===================================
# 日志配置
logging:
  # 日志级别
  level:
    root: INFO
    org.springframework.web: INFO
    com.platon: DEBUG
  file:
    # 日志文件名格式
    name: ./logs/${spring.application.name}.log
  pattern:
    # 日志记录格式[组件名称] [时间戳] [日志级别] [类名.方法名] [消息文本]
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %C / %line - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %C / %line - %msg%n'
  logback:
    rollingpolicy:
      # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
      file-name-pattern: ./logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz
      # 最大日志文件大小(默认为10MB)
      max-file-size: 200MB
      # 要保留的日志备份的总大小(默认为0B)
      # total-size-cap: 1GB
      # 保存存档日志文件的最大天数(默认为7天)
      # max-history: 20

# =============================== conf for scheduled task ===================================
LocalCarrierStatusRefreshTask.fixedDelay: 20000
LocalDataAuthReqRefreshTask.fixedDelay: 20000
LocalDataNodeRefreshTask.fixedDelay: 2000
LocalMetaDataStatusRefreshTask.fixedDelay: 10000
LocalPowerNodeRefreshTask.fixedDelay: 10000
LocalTaskRefreshTask.fixedDelay: 20000
SeedNodeRefreshTask.fixedDelay: 30000

# 超时时间，单位：秒
grpc-client-timeout: 5
