# ==================================== tidb conf  ==========================================
spring:
  application:
    name: metis-admin
  profiles:
    active: dev
  servlet:
    multipart:
      file-size-threshold: 1099511627776
      max-file-size: 1099511627776
      max-request-size: 1099511627776

# ==================================== conf for mybatis =====================================
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.platon.metis.admin.dao.entity

# ==================================== conf for pageHelper =====================================
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

