# ==================================== tidb conf  ==========================================
spring:
  profiles:
    active: dev
# ==================================== server conf  ==========================================
server:
  tomcat:
    uri-encoding: UTF-8
    threads.max: 1000
    threads.min-spare: 30
    max-swallow-size: -1
  port: 8080
  servlet:
    context-path: /rosettanet-admin

# ==================================== conf for mybatis =====================================
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.platon.rosettanet.admin.dao.entity

# ==================================== conf for pageHelper =====================================
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# =============================== conf for logger ===================================
logging:
  level: DEBUG
  level.com.platon: DEBUG
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}[%line] - %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}[%line] - %msg%n'
  file:
    name: logs/admin.log