# ==================================== server conf  ==========================================
server:
  tomcat:
    uri-encoding: UTF-8
    threads.max: 1000
    threads.min-spare: 30
  port: 9090
  servlet:
    context-path: /datum-admin

# ==================================== tidb conf  ==========================================
spring:
  application:
    name: datum-admin
  servlet:
    multipart:
      file-size-threshold: 1099511627776
      max-file-size: 10MB
      max-request-size: 1099511627776
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.9.192:3306/datum_admin_lsy?useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 6qY7CBQo7p!
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 60000
      connection-init-sqls: set names utf8mb4
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
    # =============================== consul ===============================
  cloud:
    consul:
      host: 39.101.171.59
      port: 8500
      discovery:  # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        service-name: adminService
        instance-id: adminService_39.101.171.59_9090
        tags: admin
        health-check-interval: 10s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/${server.servlet.context-path}/health
        # health-check-path: ${management.endpoints.web.base-path}/health
      carrierServiceName: carrierService

# ==================================== conf for mybatis =====================================
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.platon.datum.admin.dao.entity

# ==================================== conf for pageHelper =====================================
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# =============================== conf for swagger ===================================
swagger:
  enabled: false

# =============================== conf for logger ===================================
# 日志配置
logging:
  # 日志级别
  level:
    root: INFO
    org.springframework.web: INFO
    com.platon: DEBUG
  file:
    # 日志文件名格式
    name: ./logs/${spring.application.name}.log
  pattern:
    # 日志记录格式[组件名称] [时间戳] [日志级别] [类名.方法名] [消息文本]
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %C / %line - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %C / %line - %msg%n'
  logback:
    rollingpolicy:
      # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
      file-name-pattern: ./logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz
      # 最大日志文件大小(默认为10MB)
      max-file-size: 200MB
      # 要保留的日志备份的总大小(默认为0B)
      # total-size-cap: 1GB
      # 保存存档日志文件的最大天数(默认为7天)
      # max-history: 20

# =============================== conf for scheduled task ===================================
AttributeDataTokenInventoryRefreshTask.fixedDelay: 5000
AttributeDataTokenStatusRefreshTask.fixedDelay: 5000
AuthorityRefreshTask.fixedDelay: 5000
CarrierStatusRefreshTask.fixedDelay: 20000
DataAuthReqRefreshTask.fixedDelay: 5000
DataNodeRefreshTask.fixedDelay: 20000
DataTokenStatusRefreshTask.fixedDelay: 5000
GlobalOrgRefreshTask.fixedDelay: 20000
MetaDataStatusRefreshTask.fixedDelay: 5000
PowerNodeRefreshTask.fixedDelay: 20000
SeedNodeRefreshTask.fixedDelay: 20000
TaskRefreshTask.fixedDelay: 5000

# gprc客户端缺省超时时间，单位：秒
grpc-client-timeout: 5

# gprc客户端上传文件超时时间，单位：秒
grpc-client-upload-file-timeout: 60

#调用pinata接口的jwt
pinata-token: xxx
#pinata的网关地址
pinata-gateway: https://datumdev.mypinata.cloud/
#pinata的上传文件域名
pinata-url: https://api.pinata.cloud/

#无属性数据凭证消耗量更新间隔，单位分钟
dataToken-updateFee-interval: 5

# ==================================== conf for grpc =====================================
grpc:
  server:
    port: 9091
    in-process-name: datum-admin-server
    max-inbound-message-size: 1073741824
  client:
    #允许客户端在同一应用程序内使用以下配置连接到服务器
    inProcess:
      address: in-process:datum-admin-server

# ==================================== conf for chain =====================================
#platon:
#  web3j:
#    protocol: http
#    url: 35.247.155.162:6789
#    gasPrice: 10000000000
#    gasLimit: 4700000
#    chainHrp: lat
#    chainId: 210309
#    contractPrivateKey: 68efa6466edaed4918f0b6c3b1b9667d37cad591482d672e8abcb4c5d1720f89
#    adminAddress: lat1d7zjh2vx8xsqrgc4qe0v4usxn368naxvlpu70r
#    adminServiceUrl: https://github.com/
#
#contract:
#  vote:
#    address: lat1pgpne286589mrpx3j6n35zaw6akwfy7txheey9
#  did:
#    address: lat1l4ne2lmpl8x84pw6wet76z65kzjcvu3rsdhzj7
#  pct:
#    address: lat16ncqgyy7mqyhew6xm0fzxdqfdkehkh8xhgq3wc
#  credential:
#    address: lat1a8k45et75dr5l5hne3qwjw35wzny8eswn4jzp5