# ==================================== tidb conf  ==========================================
spring:
  application:
    name: metis-admin
  profiles:
    active: dev_10_151
  servlet:
    multipart:
      file-size-threshold: 1099511627776
      max-file-size: 1099511627776
      max-request-size: 1099511627776
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# ==================================== server conf  ==========================================
server:
  tomcat:
    uri-encoding: UTF-8
    threads.max: 1000
    threads.min-spare: 30
  port: 8080
  servlet:
    context-path: /metis-admin

# ==================================== conf for mybatis =====================================
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.platon.metis.admin.dao.entity

# ==================================== conf for pageHelper =====================================
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

